### DISCUSSION TITLE
How to use `main` branch?

### DISCUSSION THREAD

**Discussion by notramo** [martenframework/marten#222] [General]
How to try `main` branch in a project together with `marten_auth`?
If I set `shard.yaml` to this:
```yaml
  marten:
    github: martenframework/marten
    branch: main
```
then it gives the following error:
```
Unable to satisfy the following requirements:

- `marten (branch main)` required by `shard.yml`
- `marten (>= 0.2.0)` required by `marten_auth 0.2.1`
Failed to resolve dependencies
```

**Comment by ellmetha** [comment]
Hey! 👋 

We have some documentation on [how do use the Marten development version](https://martenframework.com/docs/next/the-marten-project/contributing#setting-up-a-test-project-with-marten) when contributing to Marten - which is a bit of a different use case. The similarity is that you'll want to define [shard overrides](https://crystal-lang.org/reference/1.10/man/shards/index.html#fixing-dependency-version-conflicts) by creating a `shard.override.yml` file (in addition to your `shard.yml` file) with the following content:

```yaml
dependencies:
  marten:
    github: martenframework/marten
    branch: main
```

This will force the installation of the Marten development version in your project when you run `shards install`.

Let me know if this works!

**Reply by notramo** [reply]
The problem is that `marten_auth` is not compatible with the development version of `marten`, so the installation fails with the above error message.

**Reply by ellmetha** [reply]
You would get the error message in your first message if you didn't define a `shard.override.yml` file. Can you make sure you have the `shard.override.yml` file defined in your project? Another thing worth mentioning is that your `shard.yml` file **should not** reference the `main` branch of Marten.

FWIW I just tested the solution I highlighted in my above message and it works perfectly well (including with projects making use of `marten_auth`). Can you verify that the following steps work for you?

1. Create a project with the built-in authentication:

```bash
$ marten new project myproject --with-auth
```

2. CD into the new project directory and make sure your `shard.yml` file looks something like this:

```yaml
name: myproject
version: 0.1.0

dependencies:
  marten:
    github: martenframework/marten
  marten_auth:
    github: martenframework/marten-auth
    version: ">= 0.2.0"
  sqlite3:
    github: crystal-lang/crystal-sqlite3
```

3. Define a `shard.override.yml` file with the following content:

```yaml
dependencies:
  marten:
    github: martenframework/marten
    branch: main
```

4. Install the shards:

```bash
$ shards install
```

5. Start the project' server:

```bash
$ marten serve
```
