### DISCUSSION TITLE
How can user improve compilation time?

### DISCUSSION THREAD

**Discussion by miry** [martenframework/marten#299] [Ideas]
Currently, the build time for the primitive application in GitHub Actions is around 20 minutes and 15 minutes with cache.

In my app, I’m not using all features provided by Marten—for example, storage or image field types.
I'm wondering if there’s something that can be done within the core Marten framework to load only the necessary files and dependencies.

I believe breaking the framework into smaller, optional components that can be added as needed would help optimize load times by including only the essentials.

Example of my current shard.yml:

```
dependencies:
  awscr-s3:
    github: taylorfinnell/awscr-s3
    branch: master

  marten:
    github: martenframework/marten
    branch: master

  pg:
    github: will/crystal-pg
    branch: master

  jwt:
    github: crystal-community/jwt
```
