### ISSUE TITLE
Add an `--edge` option to the `new` management command

### ISSUE THREAD

**Issue by ellmetha** [martenframework/marten#224]
# Description

Let's make it possible to generate new projects (or applications) that use the development version of Marten through the use of an `--edge` / `-e` option. When this option is set, the generated project structure should include a `shard.override.yml` file (in addition to the `shard.yml` file) with the following content:

```yaml
dependencies:
  marten:
    github: martenframework/marten
    branch: main
```

This will ensure that the project uses the development version of Marten (`main` branch) when running the `shards install` command ([ref](https://crystal-lang.org/reference/1.12/man/shards/index.html#fixing-dependency-version-conflicts)).
